server:
  port: 7002
spring:
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.20.39.153:33061/db_am4?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
feign:
  httpclient:
    enabled: true
